services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    
    buildFilter:
      - pip install gunicorn  # Install Gunicorn during the build process
    startCommand: gunicorn myproject.wsgi
    systemDependencies:
      - python3-tk