"""
Django settings for justeco project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.conf import settings





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n(_9tj%y&(0kzf39tbj-z8vqm0pvc9qi(y7c^jp4-wg&+x=0(%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_resized',
    'registrationuser',
    'adminapp',
    'products',
    'categories',
    'brand',
    'home',
    'cart',
    'order',
    'checkout',
    'wishlist',
    'userprofile',
    'shop',
    'coupon',
    'banner',
    'offer',
    'mathfilters',
    'twilio',
    
    
    
    
]
# from easy_thumbnails import defaults
# THUMBNAIL_PROCESSORS = (
#     'image_cropping.thumbnail_processors.crop_corners',
# ) + defaults.PROCESSORS




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'justeco.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.cart_and_wishlist_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'justeco.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'seconddb',
#        'USER': 'postgres',
#        'PASSWORD': '12345',
#        'HOST': 'localhost',
#        'PORT': '5432',
#    }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = 'justwatches/justecommerce/static/'

# Set session engine to use database-backed sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Set the session age (optional)
# Set the session age to None to use the default session age set in settings.SESSION_COOKIE_AGE

SESSION_COOKIE_AGE = 7 * 24 * 60 * 60

STATIC_URL = 'static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR/'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py

TWILIO_ACCOUNT_SID = 'AC85eaedafa42150fcc6f8b1acda27c129'
TWILIO_AUTH_TOKEN = 'e1d2862ca859b58300947e6a3981e9a2'


# Email Configuration
# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # e.g., smtp.gmail.com
EMAIL_PORT = 587  # check your SMTP provider for the correct port
EMAIL_HOST_USER = 'mishalmp916@gmail.com'
EMAIL_HOST_PASSWORD = 'bvspramnxxydjsqp'
EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



RAZORPAY_KEY_ID = 'rzp_test_4vQTEjTZ9mHK3d'
RAZORPAY_KEY_SECRET = '0mcpiXgs9jiOppGgbFZQ3mdk'