# Generated by Django 4.2.1 on 2023-07-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='No image available', null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(default='No image available', null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(default='No image available', null=True, upload_to='photos/product'),
        ),
    ]
