# Generated by Django 4.2.1 on 2023-06-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='No image available', upload_to='photos/product'),
        ),
    ]
