# Generated by Django 4.2.1 on 2023-06-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_pricefilter_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(default='No image available', upload_to='photos/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(default='No image available', upload_to='photos/product'),
        ),
    ]
