# Generated by Django 4.2.1 on 2023-07-11 12:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_product_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[300, 300], upload_to='photos/product'),
        ),
    ]
