# Generated by Django 4.2.3 on 2023-08-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
