# Generated by Django 4.2.1 on 2023-06-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_address',
        ),
    ]
